project:
  type: website

website:
  title: "Mark Druffel"
  description: "Data scientist, askew of central tendencies"
  site-url: https://www.mark-druffel.com
  favicon: images/initials.ico
  open-graph: true
  twitter-card: 
    creator: "@MarkDruffel"
  navbar:
    title: false
    search: true
    left:
      - text: "Blog"
        file: blog.qmd
      - text: "About Me"
        file: about.qmd
      - text: "Resume"
        file: resume.html
    right:
      - icon: github
        href: https://github.com/mark-druffel
      - icon: linkedin
        href: https://linkedin.com/in/markdruffel
      - icon: stack-overflow
        href: https://stackoverflow.com/users/6213809/mark-druffel
      - icon: twitter
        href: https://twitter.com/MarkDruffel
      - icon: instagram
        href: https://www.instagram.com/markdruffel/
      - icon: envelope 
        href: mailto:mark.druffel@gmail.com?subject=mark-druffel.com
  comments:
      giscus:
        repo: mark-druffel/www.mark-druffel.com
        category: "Announcements"

format:
  html:
    theme: 
      light: [flatly, css/theme.scss]
      dark: [darkly, css/theme.scss, css/darkly.scss]
    



